const actions = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  GET_AUTH_USER: 'GET_AUTH_USER',
  GET_AUTH_USER_SUCCESS: 'GET_AUTH_USER_SUCCESS',
  GET_AUTH_USER_FAILURE: 'GET_AUTH_USER_FAILURE',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_LISTNER: 'LOGIN_LISTNER',
  LOGIN_SUCCESS_LISTNER: 'LOGIN_SUCCESS_LISTNER',
  LOGIN_FAILURE_LISTNER: 'LOGIN_FAILURE_LISTNER',
  GET_AUTH_USER_LISTNER: 'GET_AUTH_USER_LISTNER',
  GET_AUTH_USER_SUCCESS_LISTNER: 'GET_AUTH_USER_SUCCESS_LISTNER',
  GET_AUTH_USER_FAILURE_LISTNER: 'GET_AUTH_USER_FAILURE_LISTNER',
  LOGOUT_LISTNER: 'LOGOUT_LISTNER',
  LOGOUT_SUCCESS_LISTNER: 'LOGOUT_SUCCESS_LISTNER',
  LOGOUT_FAILURE_LISTNER: 'LOGOUT_FAILURE_LISTNER',
  REGISTER_LISTNER: 'REGISTER_LISTNER',
  REGISTER_SUCCESS_LISTNER: 'REGISTER_SUCCESS_LISTNER',
  REGISTER_FAILURE_LISTNER: 'REGISTER_FAILURE_LISTNER',
}

export default actions;
